[build]
  command = "npm run build"
  publish = "public/"

[context.dry]
  command = ""
  publish = "/"
  
[[redirects]]
  from = "/posts/installing-node-tiddlywiki-on-an-ubuntu-vps"
  to = "/writing/installing-node-tiddlywiki-on-an-ubuntu-vps"
[[redirects]]
  from = "/posts/using-open-source-news-apps-for-non-profits-and-advocacy"
  to = "/writing/using-open-source-news-apps-for-non-profits-and-advocacy"
[[redirects]]
  from = "/posts/closures"
  to = "/writing/closures"
