[build]
  command = "npm run build"
  publish = "public/"

[context.dry]
  command = ""
  publish = "/"
  
[[redirects]]
  from = "/writing/installing-node-tiddlywiki-on-an-ubuntu-vps"
  to = "/posts/installing-node-tiddlywiki-on-an-ubuntu-vps"
